language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0snapshot

env:
  global:
    - setup=basic
    - APP_ENV=testing

sudo: false

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update --2

cache:
  directories:
    - $HOME/.composer/cache

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --ignore-platform-req=php; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --ignore-platform-req=php; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --ignore-platform-req=php; fi

script: vendor/bin/phpunit --verbose
